## Assignment 2

# 1. Sampling from Uniform[-1,1]

In [50]:
phi.ball <- function( x ){ # actually a simplex
    


  return( sum(x*x)<=1 );
    
}

In [343]:
## Run the Monte Carlo method
## nn points 
## with phi a boolean function 

vol_monteCarlo <- function( 
  nn=500, dd=4, phi, PLOT_GRID=F 
){
  # generate nn * dd uniform random variables
  mcGrid <- matrix(
    runif( nn*dd,0,1 ), nrow=nn, ncol=dd 
  );
  
  # Apply phi to each row in mcGrid
  # to determine if the point is in region D
  inRegion <- apply( mcGrid, 1, phi )
  
    
  est = sum(inRegion)/nn;
  return( 
    c( 
      est*2^dd,                 # estimate for vol(D)
      est*(1-est)/(nn-1)   # estimate variance
    )
  )
}


vol_compConfInt <- function( est, vari, nn, alf ){
  norm = c(est - qnorm(1-alf/2)*sqrt(vari), est, est + qnorm(1-alf/2)*sqrt(vari) )
  cheb = c(est - sqrt(4*nn*alf)^(-1), est, est + sqrt(4*nn*alf)^(-1) )
  hoef = c(est - sqrt(-log(alf/2)/(2*nn)), est, est + sqrt(-log(alf/2)/(2*nn)) )
  return(
    rbind( norm,cheb,hoef )
  )}


In [344]:
# Try nn = 3600 and dimensions = 4
nn = 36000

out = vol_monteCarlo( nn=nn, dd=4, phi=phi.ball, PLOT_GRID = T )
print(paste("Est  volume = ",out[1]))
print(paste("True volume = ",(pi^2)/2))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "Est  volume =  4.91288888888889"
[1] "True volume =  4.93480220054468"
[1] "Variance =  5.91050977410552e-06"


[,1]     [,2]     [,3]    
norm 4.908124 4.912889 4.917654
cheb 4.901104 4.912889 4.924674
hoef 4.905731 4.912889 4.920047

In [25]:
# Try nn = 3600 and dimensions = 10
nn = 36000

out = vol_monteCarlo( nn=nn, dd=10, phi=phi.ball, PLOT_GRID = T )
print(paste("Est  volume = ",out[1]))
print(paste("True volume = ",(2.55016404)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "Est  volume =  2.58844444444444"
[1] "True volume =  2.55016404"
[1] "Variance =  7.00405043830093e-08"


[,1]     [,2]     [,3]    
norm 2.587926 2.588444 2.588963
cheb 2.576659 2.588444 2.600230
hoef 2.581287 2.588444 2.595602

# 2. Beta(1/2,1/2)

In [164]:
scaledf_density <- function( y,d ){ 
    
    
    return (  (1/(2*pi)) * 1/( (sqrt((y+1)/2)*sqrt(1-((y+1)/2))) )  );
    
    
    
}

In [183]:
## Run the Monte Carlo method
## nn points 
## with phi a boolean function 



vol_monteCarloBeta <- function( 
  nn=5000, dd=4, nu=1/2, phi, PLOT_GRID=F 
){
  # generate nn * dd beta random variables

  mcGrid <- matrix(
    2*rbeta( nn*dd, shape1 = 1/2, shape2 = 1/2 )-1 , nrow=nn, ncol=dd 
  );
  
  # Apply phi to each row in mcGrid
  # to determine if the point is in region D
  inRegion <- apply( mcGrid, 1, phi )
  
  # Compute beta weights
    
  
 
  #betaWeight <- dbeta( mcGrid, shape1 = 1/2, shape2 = 1/2 )
    
  betaWeight = scaledf_density(mcGrid,dd)
    
    
  betaWeight <- apply( betaWeight, 1, prod )
    


  if( PLOT_GRID & (dd==2) )
    plot(
      mcGrid, xlim=c(0,1),ylim=c(0,1),las=1,
      col = c("gray","red")[inRegion+1],pch=16
    )
    
  # Weighted Mean
  est = mean(inRegion/betaWeight)
  vari= var(inRegion/betaWeight)/(nn-1)
  return( 
    c( 
      est,   # estimate for vol(D)
      vari   # estimate variance
    )
  )
}



vol_compConfInt <- function( est, vari, nn, alf ){
  norm = c(est - qnorm(1-alf/2)*sqrt(vari), est, est + qnorm(1-alf/2)*sqrt(vari) )
  cheb = c(est - sqrt(4*nn*alf)^(-1), est, est + sqrt(4*nn*alf)^(-1) )
  hoef = c(est - sqrt(-log(alf/2)/(2*nn)), est, est + sqrt(-log(alf/2)/(2*nn)) )
  return(
    rbind( norm,cheb,hoef )
  )}
  




In [184]:
# Try nn = 100, dimensions = 4
nn = 50000
out = vol_monteCarloBeta( nn=nn, dd=4, nu=2, phi=phi.ball, PLOT_GRID = F )
print("----- beta Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",4.9348))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- beta Dist,  -----"
[1] "Est  Area =  4.94880109357355"
[1] "True Area =  4.9348"
[1] "Variance =  0.00586139542256971"


[,1]     [,2]     [,3]    
norm 4.798747 4.948801 5.098855
cheb 4.938801 4.948801 4.958801
hoef 4.942727 4.948801 4.954875

In [111]:
# Try nn = 3600 and dimensions = 10
nn = 50000

out = vol_monteCarloBeta( nn=nn, dd=10, phi=phi.ball, PLOT_GRID = F )
print(paste("Est  volume = ",out[1]))
print(paste("True volume = ",(2.55016404)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "Est  volume =  2.21459008703756"
[1] "True volume =  2.55016404"
[1] "Variance =  2579886.81109531"


[,1]         [,2]    [,3]       
norm -3145.884669 2.21459 3150.313849
cheb     2.204590 2.21459    2.224590
hoef     2.208516 2.21459    2.220664

# 3. Beta(2,2)

In [191]:
scaledf_density2 <- function( y ){ 
    
    
    return(  3*( (y+1)/2)*( 1- ( (y+1)/2))              );
    
    
    
}

In [189]:
## Run the Monte Carlo method
## nn points 
## with phi a boolean function 



vol_monteCarloBeta22 <- function( 
  nn=5000, dd=4, nu=2, phi, PLOT_GRID=F 
){
  # generate nn * dd beta random variables

  mcGrid <- matrix(
    2*rbeta( nn*dd, shape1 = 2, shape2 = 2 )-1 , nrow=nn, ncol=dd 
  );
  
  # Apply phi to each row in mcGrid
  # to determine if the point is in region D
  inRegion <- apply( mcGrid, 1, phi )
  
  # Compute beta weights
    
  
 
  #betaWeight <- dbeta( mcGrid, shape1 = 1/2, shape2 = 1/2 )
    
  betaWeight <- scaledf_density2(mcGrid)
    
    
  betaWeight <- apply( betaWeight, 1, prod )
    


  if( PLOT_GRID & (dd==2) )
    plot(
      mcGrid, xlim=c(0,1),ylim=c(0,1),las=1,
      col = c("gray","red")[inRegion+1],pch=16
    )
    
  # Weighted Mean
  est = mean(inRegion/betaWeight)
  vari= var(inRegion/betaWeight)/(nn-1)
  return( 
    c( 
      est,   # estimate for vol(D)
      vari   # estimate variance
    )
  )
}



vol_compConfInt <- function( est, vari, nn, alf ){
  norm = c(est - qnorm(1-alf/2)*sqrt(vari), est, est + qnorm(1-alf/2)*sqrt(vari) )
  cheb = c(est - sqrt(4*nn*alf)^(-1), est, est + sqrt(4*nn*alf)^(-1) )
  hoef = c(est - sqrt(-log(alf/2)/(2*nn)), est, est + sqrt(-log(alf/2)/(2*nn)) )
  return(
    rbind( norm,cheb,hoef )
  )}
  




In [192]:
# Try nn = 100, dimensions = 4
nn = 50000
out = vol_monteCarloBeta22( nn=nn, dd=4, nu=2, phi=phi.ball, PLOT_GRID = F )
print("----- beta Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",4.9348))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- beta Dist,  -----"
[1] "Est  Area =  4.92462004239008"
[1] "True Area =  4.9348"
[1] "Variance =  0.000338956501417036"


[,1]     [,2]    [,3]    
norm 4.888536 4.92462 4.960704
cheb 4.914620 4.92462 4.934620
hoef 4.918546 4.92462 4.930694

In [346]:
# Try nn = 3600 and dimensions = 10
nn = 50000

out = vol_monteCarloBeta22( nn=nn, dd=10, phi=phi.ball, PLOT_GRID = F )
print(paste("Est  volume = ",out[1]))
print(paste("True volume = ",(2.55016404)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "Est  volume =  2.44601068736554"
[1] "True volume =  2.55016404"
[1] "Variance =  0.00215571667383763"


[,1]     [,2]     [,3]    
norm 2.355010 2.446011 2.537011
cheb 2.436011 2.446011 2.456011
hoef 2.439937 2.446011 2.452084

 # 2: Computing the Bessel function

# 1. from Unif[-1,1]

In [303]:
besselFunc <- function( m,x,t ){
    return(     cos((m*t) - x*sin(t))     );
}

In [241]:
## Run the Monte Carlo method
## nn points 
## with phi a boolean function 



besselunif <- function( 
  nn=5000, x=1, m=1,  PLOT_GRID=F 
){
  # generate nn * dd beta random variables

  xx <- runif(nn,0,pi)
  
  # Apply phi to each row in mcGrid
  # to determine if the point is in region D
  val <- besselFunc(m,x,xx)
    
  
  

    
  est = mean(val)
  vari= var(val)
  return( 
    c( 
      est,   # estimate for integral of bessel function
      vari   # estimate variance
    )
  )
}



vol_compConfInt <- function( est, vari, nn, alf ){
  norm = c(est - qnorm(1-alf/2)*sqrt(vari), est, est + qnorm(1-alf/2)*sqrt(vari) )
  cheb = c(est - sqrt(4*nn*alf)^(-1), est, est + sqrt(4*nn*alf)^(-1) )
  hoef = c(est - sqrt(-log(alf/2)/(2*nn)), est, est + sqrt(-log(alf/2)/(2*nn)) )
  return(
    rbind( norm,cheb,hoef )
  )}
  



In [310]:
# Try with m=1,x=1
nn = 50000
out = besselunif( nn=nn,  x=1, m=1, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(1,1)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )


[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.435131206976375"
[1] "True Area =  0.440050585744934"
[1] "Variance =  0.487362978881403"


[,1]       [,2]      [,3]     
norm -0.9331468 0.4351312 1.8034093
cheb  0.4251312 0.4351312 0.4451312
hoef  0.4290576 0.4351312 0.4412048

In [315]:
# Try with m=2,x=2
nn = 50000
out = besselunif( nn=nn,  x=2, m=2, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(2,2)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.358893242776897"
[1] "True Area =  0.352834028615638"
[1] "Variance =  0.51381201886117"


[,1]       [,2]      [,3]     
norm -1.0460223 0.3588932 1.7638088
cheb  0.3488932 0.3588932 0.3688932
hoef  0.3528196 0.3588932 0.3649669

In [347]:
# Try with m=2,x=2
nn = 50000
out = besselunif( nn=nn,  x=4, m=4, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(4,4)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.27780709872202"
[1] "True Area =  0.28112906496136"
[1] "Variance =  0.530929408685231"


[,1]       [,2]      [,3]     
norm -1.1503188 0.2778071 1.7059330
cheb  0.2678071 0.2778071 0.2878071
hoef  0.2717335 0.2778071 0.2838807

# 2. from Beta(1/2,1/2)

In [278]:
density <- function( y ){ 
    
    
    return(   (1/(pi*pi))*(1/(sqrt(y/pi)))*(1/sqrt(1-(y/pi)))  );
    
    
    
}

In [322]:
## Run the Monte Carlo method
## nn points 
## with phi a boolean function 



besselbeta <- function( 
  nn=5000, x=1, m=1,  PLOT_GRID=F 
){
  # generate nn * dd beta random variables

  xx <- rbeta(nn,shape1=1/2,shape2=1/2)*pi
    
 
    
  
    
  
  
  # Apply phi to each row in mcGrid
  # to determine if the point is in region D
  val <- besselFunc(m,x,xx)
    
  ww  <- density(xx)
    
  
  

    
  est = mean(val*(1/pi)/ww)
  vari= var(val*(1/pi)/ww)
  return( 
    c( 
      est,   # estimate for integral of bessel function
      vari   # estimate variance
    )
  )
}



vol_compConfInt <- function( est, vari, nn, alf ){
  norm = c(est - qnorm(1-alf/2)*sqrt(vari), est, est + qnorm(1-alf/2)*sqrt(vari) )
  cheb = c(est - sqrt(4*nn*alf)^(-1), est, est + sqrt(4*nn*alf)^(-1) )
  hoef = c(est - sqrt(-log(alf/2)/(2*nn)), est, est + sqrt(-log(alf/2)/(2*nn)) )
  return(
    rbind( norm,cheb,hoef )
  )}
  


In [324]:
# Try with m=1,x=1
nn = 5000
out = besselbeta( nn=nn,  x=1, m=1, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(1,1)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )


[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.440463198692848"
[1] "True Area =  0.440050585744934"
[1] "Variance =  0.601555339344559"


[,1]       [,2]      [,3]     
norm -1.0796848 0.4404632 1.9606112
cheb  0.4088404 0.4404632 0.4720860
hoef  0.4212567 0.4404632 0.4596697

In [326]:
# Try with m=2,x=2
nn = 5000
out = besselbeta( nn=nn,  x=2, m=2, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(2,2)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.349342790897357"
[1] "True Area =  0.352834028615638"
[1] "Variance =  0.625468451083052"


[,1]       [,2]      [,3]     
norm -1.2007254 0.3493428 1.8994110
cheb  0.3177200 0.3493428 0.3809656
hoef  0.3301363 0.3493428 0.3685492

In [330]:
# Try with m=4,x=4
nn = 5000
out = besselbeta( nn=nn,  x=4, m=4, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(4,4)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.26337816324579"
[1] "True Area =  0.28112906496136"
[1] "Variance =  0.636845151679048"


[,1]       [,2]      [,3]     
norm -1.3007236 0.2633782 1.8274800
cheb  0.2317554 0.2633782 0.2950009
hoef  0.2441717 0.2633782 0.2825846

# 3: from Beta(2,2)

In [331]:
density2 <- function( y ){ 
    
    
    return(     (1/pi)*6*(y/pi)*(1-(y/pi))    );
    
    
    
}

In [333]:
## Run the Monte Carlo method
## nn points 
## with phi a boolean function 



besselbeta2 <- function( 
  nn=5000, x=1, m=1,  PLOT_GRID=F 
){
  # generate nn * dd beta random variables

  xx <- rbeta(nn,shape1=2,shape2=2)*pi
    
 
    
  
    
  
  
  # Apply phi to each row in mcGrid
  # to determine if the point is in region D
  val <- besselFunc(m,x,xx)
    
  ww  <- density2(xx)
    
  
  

    
  est = mean(val*(1/pi)/ww)
  vari= var(val*(1/pi)/ww)
  return( 
    c( 
      est,   # estimate for integral of bessel function
      vari   # estimate variance
    )
  )
}



vol_compConfInt <- function( est, vari, nn, alf ){
  norm = c(est - qnorm(1-alf/2)*sqrt(vari), est, est + qnorm(1-alf/2)*sqrt(vari) )
  cheb = c(est - sqrt(4*nn*alf)^(-1), est, est + sqrt(4*nn*alf)^(-1) )
  hoef = c(est - sqrt(-log(alf/2)/(2*nn)), est, est + sqrt(-log(alf/2)/(2*nn)) )
  return(
    rbind( norm,cheb,hoef )
  )}
  


In [334]:
# Try with m=1,x=1
nn = 5000
out = besselbeta2( nn=nn,  x=1, m=1, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(1,1)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )


[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.450071733471133"
[1] "True Area =  0.440050585744934"
[1] "Variance =  1.37818583133275"


[,1]       [,2]      [,3]     
norm -1.8508507 0.4500717 2.7509942
cheb  0.4184490 0.4500717 0.4816945
hoef  0.4308653 0.4500717 0.4692782

In [340]:
# Try with m=2,x=2
nn = 5000
out = besselbeta2( nn=nn,  x=2, m=2, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(2,2)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )


[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.333380440275692"
[1] "True Area =  0.352834028615638"
[1] "Variance =  0.937554004463737"


[,1]       [,2]      [,3]     
norm -1.5644012 0.3333804 2.2311621
cheb  0.3017577 0.3333804 0.3650032
hoef  0.3141740 0.3333804 0.3525869

In [342]:
# Try with m=4,x=4
nn = 5000
out = besselbeta2( nn=nn,  x=4, m=4, PLOT_GRID = F )
print("----- Uniform Dist,  -----")
print(paste("Est  Area = ",out[1]))
print(paste("True Area = ",besselJ(4,4)))
print(paste("Variance = ",out[2]))
vol_compConfInt( out[1], out[2], nn, 0.05 )

[1] "----- Uniform Dist,  -----"
[1] "Est  Area =  0.288349274309623"
[1] "True Area =  0.28112906496136"
[1] "Variance =  2.22414960396902"


[,1]       [,2]      [,3]     
norm -2.6346593 0.2883493 3.2113578
cheb  0.2567265 0.2883493 0.3199721
hoef  0.2691428 0.2883493 0.3075557